            - name: Discord Notify
  # You may pin to the exact commit or the version.
  # uses: stegzilla/discord-notify@e9ae7f7d5d45da6be819165c3ccf78357e12bdf6
  uses: stegzilla/discord-notify@v4
  with:
    # Webhook URL from Discord
    webhook_url: # default is 
    # Title for card
    title: # optional, default is 
    # Content of card
    message: # default is 
    # If action is used in a pull request, attach the preview image for it to the card. Required for custom_image_url
    include_image: # optional, default is false
    # Avatar to use for user
    avatar_url: # optional, default is 
    # Username to send message as
    username: # optional, default is GitHub
    # Colour for the edge of the card in hex
    colour: # optional, default is #3371FF
    # Include custom image on card, include_image must be true
    custom_image_url: # optional, default is 
    # Make the title of the card a link
    title_url: # optional, default is 
          
